export enum EventType {
  FLOOD = "FLOOD",
  DROUGHT = "DROUGHT",
  CONFLICT = "CONFLICT",
  EARTHQUAKE = "EARTHQUAKE",
  TSUNAMI = "TSUNAMI",
  INDUSTRIAL_ACCIDENT = "INDUSTRIAL_ACCIDENT",
  LANDSLIDE = "LANDSLIDE",
  OTHER = "OTHER"


}
