export const MapZoomLevels = {
  DEFAULT_MAX_ZOOM: 17,
  DEFAULT_MIN_ZOOM: 0,
  IMAGERY_MAX_ZOOM: 19,
  IMAGERY_MIN_ZOOM: 0,
  STREET_MAX_ZOOM: 19,
  STREET_MIN_ZOOM: 0,
  DARK_MAX_ZOOM: 16,
  DARK_MIN_ZOOM: 0,
  STANDARD_MAX_ZOOM: 19,
  STANDARD_MIN_ZOOM: 0,
}
