export const MapZoomLevels = {
  DEFAULT_MAX_ZOOM: 19,
  DEFAULT_MIN_ZOOM: 3,
  IMAGERY_MAX_ZOOM: 18,
  IMAGERY_MIN_ZOOM: 3,
  STREET_MAX_ZOOM: 19,
  STREET_MIN_ZOOM: 3,
  DARK_MAX_ZOOM: 16,
  DARK_MIN_ZOOM: 3,
  STANDARD_MAX_ZOOM: 16,
  STANDARD_MIN_ZOOM: 3,
}
